import type { Metadata } from "next";
import { PageHero } from "@/components/shared/PageHero";
import { Container } from "@/components/shared/Container";
import { AnimatedSection } from "@/components/shared/AnimatedSection";
import { MotionSectionBridge } from "@/components/shared/MotionSectionBridge";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for Ebenezer Ethiopian Church website and forms.",
  robots: { index: true, follow: true },
};

export default function PrivacyPage() {
  const effectiveDate = "April 19, 2026";

  return (
    <div className="relative overflow-x-hidden">
      <PageHero
        eyebrow="Legal"
        title="Privacy policy"
        description="How Ebenezer Ethiopian Church collects, uses, stores, and protects personal information."
      />
      <MotionSectionBridge variant="fromNavy" />
      <AnimatedSection className="py-16 sm:py-24">
        <Container className="max-w-3xl">
          <div className="space-y-8 leading-relaxed text-charcoal-700">
            <p className="text-sm text-charcoal-600">Effective date: {effectiveDate}</p>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">1. Who we are</h2>
              <p>
                Ebenezer Ethiopian Church ("we," "our," or "us") operates this website to
                share ministry information, receive messages, and support church
                participation. This policy explains how we handle personal information.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">2. Information we collect</h2>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  <span className="font-medium text-navy-950">Contact details:</span> name,
                  email address, phone number, and message content submitted through contact
                  forms.
                </li>
                <li>
                  <span className="font-medium text-navy-950">Prayer request content:</span>{" "}
                  information you choose to provide in prayer forms.
                </li>
                <li>
                  <span className="font-medium text-navy-950">Membership form details:</span>{" "}
                  profile and church-history information submitted through membership
                  workflows.
                </li>
                <li>
                  <span className="font-medium text-navy-950">Giving-related data:</span>{" "}
                  when you use third-party giving providers, payment processing data is
                  collected by those providers, not directly by this website.
                </li>
                <li>
                  <span className="font-medium text-navy-950">Basic technical data:</span>{" "}
                  browser/device information and similar logs generated by normal website
                  operations.
                </li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">3. How we use information</h2>
              <ul className="list-disc space-y-2 pl-5">
                <li>Respond to inquiries, prayer requests, and ministry follow-up.</li>
                <li>Process membership and engagement requests.</li>
                <li>Provide church communications you request.</li>
                <li>Administer church operations and improve website usability.</li>
                <li>Maintain security and prevent misuse of our systems.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">
                4. Third-party services
              </h2>
              <p>
                We use trusted third-party providers for certain services (for example,
                online giving and external form processing). Information submitted through
                those services is governed by their own privacy policies and terms.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">
                5. Data sharing and disclosure
              </h2>
              <p>We do not sell personal information.</p>
              <p>
                We may share limited information only when necessary to operate church
                ministries, provide requested services, comply with legal obligations, or
                protect the safety and integrity of our congregation and systems.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">
                6. Data retention and security
              </h2>
              <p>
                We retain records only as long as reasonably needed for ministry,
                administrative, legal, and accountability purposes. We use reasonable
                administrative and technical safeguards to protect information, but no
                internet transmission or storage method can be guaranteed 100% secure.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">7. Your choices</h2>
              <p>
                You may request to review, correct, or delete personal information we hold,
                subject to legal, ministry, and record-keeping obligations. You may also
                opt out of non-essential communications at any time.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">8. Children</h2>
              <p>
                We encourage parents or guardians to supervise children's online activities.
                If you believe a child has provided personal information inappropriately,
                please contact us so we can review and address the request.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">
                9. Changes to this policy
              </h2>
              <p>
                We may update this policy from time to time. Updates will be posted on this
                page with a revised effective date.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-heading text-2xl text-navy-950">10. Contact</h2>
              <p>
                For privacy questions or requests, contact us through the Contact page of
                this website.
              </p>
            </section>
          </div>
        </Container>
      </AnimatedSection>
      <MotionSectionBridge variant="aurora" />
    </div>
  );
}
